ExpediaGroup/comparadise

.github/workflows/codeql-analysis.yml, .github/workflows/publish.yml, .github/workflows/test.yml, package-lock.json, package.json, server/index.ts
- Adds CodeQL code scanning
- Resolves the [first alert](https://github.com/ExpediaGroup/comparadise/security/code-scanning/1) using express-rate-limit
=> fix(security): add codeql-analysis.yml and add express rate limit

package-lock.json, package.json, src/App.tsx, src/components/ImageView.tsx
- This is unused right now so removing it
=> fix: remove react-medium-image-zoom

src/components/Main.tsx, src/components/UpdateImagesButton.tsx, src/constants.ts, src/index.tsx
=> refactor: query param cleanup

server/getGroupedImages.ts, server/listAllS3PathsForHash.ts, server/updateBaseImagesInS3.ts, src/App.css, src/components/ImageView.tsx, src/custom.d.ts, src/index.tsx, tsconfig.json
- Start type checking on client source files
=> chore: typescript cleanup

cypress/component/Main.cy.tsx, src/components/Loader.tsx, src/components/UpdateImagesButton.tsx
- Fixes an issue where during the process of updating base images, there is currently no loader displayed.
=> fix: loader for updating base images

package-lock.json, package.json
=> fix: downgrade packages to avoid docker build issue

package-lock.json, package.json
Reverts ExpediaGroup/comparadise#126
=> fix: revert downgrade packages to avoid docker build issue

package-lock.json, package.json
- https://swc.rs/docs/usage/jest
=> chore: replace ts-jest with @swc/jest

.github/workflows/test.yml, frontend/components/arrows.tsx, frontend/components/buttons.tsx
- Refactors away some duplicate code and switches color palette to island colors!
=> feat: use island colors

action/run.test.ts, cypress/tsconfig.json, tsconfig.json
=> chore: clean up tsconfigs and start typechecking jest tests

app/frontend/components/loader.tsx, app/frontend/components/main-page.tsx, app/package.json
- Preserves most of the experience while paginating the next set of images.
=> fix(app): improve loading experience during navigation

app/backend/src/fetchCurrentPage.ts, app/backend/src/schema.ts, app/backend/test/fetchCurrentPage.test.ts, app/frontend/components/main-page.tsx, app/frontend/cypress/component/App.cy.tsx, app/frontend/providers/client-provider.tsx
- Prefetch next page while on current page.
=> fix(app): prefetch next page on current page

app/frontend/components/image-views.tsx
- Fixes styling issue when there is only one image view button.
=> fix(app): styling on single image view button

pnpm-lock.yaml, pnpm-workspace.yaml
=> ci: simplify pnpm-workspace.yaml

app/frontend/package.json, comparadise-utils/package.json, pnpm-lock.yaml
=> chore(deps): clean up cypress dependencies

app/backend/src/fetchCurrentPage.ts, app/backend/src/getGroupedKeys.ts, app/backend/src/updateBaseImagesInS3.ts, app/frontend/components/image-views.tsx, app/frontend/components/main-page.tsx, tsconfig.json
=> fix(repo): set noUncheckedIndexAccess to true

action.yml
=> chore: upgrade action to use node v20

app/frontend/components/image-views.tsx
- Display loading state for individual images prior to being loaded by the browser.
=> feat(app): improve image loading experience

.github/workflows/publish.yml, app/app.tsx, app/frontend/components/main-page.tsx, app/server.tsx
=> fix(app): loading state

app/backend/src/getKeysFromS3.ts
- Does not seem like we need this, and removing this allows the app to download images properly
=> fix(app): remove delimiter

app/backend/src/updateBaseImagesInS3.ts
- Make the `getBaseImagePaths` method more understandable.
=> refactor: getBaseImagePaths method

app/frontend/cypress/e2e/home-page.cy.ts, app/server.ts
- Fixes health check and adds test
=> fix: health check

comparadise-utils/package.json, comparadise-utils/tsup.config.ts
- createBaseImage was not usable from client usage since the updated dist and commands files were not being generated
- #636
=> fix: issue with create-base-image.ts generated files not working properly
